# Change these first
owner: Webdz-Co # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: Webdz-Co

sites:
  - name: girlsinc
    url: https://girlsinc-houston.org
  - name: cookieco
    url: https://gettysburgcookieco.com
  - name: ntb
    url: https://northtexasbankruptcy.com
  - name: rebecca
    url: https://rebeccadturner.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.agencykahuna.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Webdz-Co/upptime/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our GitHub repository. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
